<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SearchEnquiry.aspx.cs" Theme="Default" MasterPageFile ="~/Enquiry/Enquiry.Master" Inherits="Enquiry.Forms.SearchEnquiry" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajax" %>
<asp:Content ID="headr" ContentPlaceHolderID="head" runat="server">
<script type="text/javascript">
    function ShowHide(id) {
        var el = document.getElementById('AdvSearch');
        var expcol = document.getElementById('imgA');
        if (el.style.display == 'none') {
            el.style.display ="";
            /*expcol.src = "Images/imgUblue.png" */
            expcol.src = "../../Billing/Images/imgUblue.PNG"
        }
        else {
            el.style.display = 'none';
            /* expcol.src = "Images/imgDblue.png" */
            expcol.src = "../../Billing/Images/imgDblue.PNG"
        }
    }    
</script>
<style type="text/css">
.popupHover
{
    background-color:#FAF8CC;
}
.LeftSide
{
  float:left;
clear:right;
height:0; 
overflow:hidden
}
</style>
</asp:Content>
 
<asp:Content ID="Enquiry" ContentPlaceHolderID="main" runat="server">  
<asp:Panel ID="SearchTable" runat="server" >
 <div style="border:solid 1px #498AF3; width:545px;" >     
    <asp:TextBox ID="txtSearch" runat="server"  BorderStyle="None"   Height="18px" Width="500px"   ></asp:TextBox>        
    <asp:ImageButton ID="search" runat="server" CssClass="vAlign" ImageUrl="~/Images/imgSBlue.gif"  OnClick="SearchBtnClick"   /><%-- --%>
    <a href="#" onclick="javascript:ShowHide(this);return false;" style="vertical-align:middle;">
    <input type="image" src="../../Images/imgDblue.PNG" id="imgA" /></a>  
    <ajax:TextBoxWatermarkExtender ID="ajaxWaterMark" runat="server" TargetControlID="txtSearch"
     WatermarkText="Search..." ></ajax:TextBoxWatermarkExtender>
    
 </div>
<div id="AdvSearch" style="border:solid 1px #AACCEE; width:50%;display:none; margin-top:5px;">
<div style="border:solid 1px #498AF3; height:20px; background-color:#498AF3; color:White;">
<div style="margin-left:5px;margin-top:2px;">
<asp:Label ID="lblSearchControl"  runat="server" Text=" Advanced Search"  SkinID="" />
</div>
</div>

<div>
<table >
    <tr>
        <td>
            ID  </td>
        <td>            
            <asp:TextBox ID="txtID" runat="server" Width="150px" ></asp:TextBox>
        </td>
        <td>
            Created By  
        </td>
        <td>
            <asp:TextBox ID="txtCreatedBy" Width="150px" runat="server"></asp:TextBox>
            
        </td>
    </tr>
    <tr>
        <td>
            Company
        </td>
        <td>
            <asp:TextBox ID="txtCompany" Width="150px" runat="server"></asp:TextBox>
        </td>
        <td>
        </td>
        <td>
          <asp:Button runat="server" ID="ClearBtn" Text="Reset" OnClick="ClearBtnClick" />
        </td>
    </tr>    
</table>
 </div>
 </div>
 
<table>
    <tr>               
        <td>
        <asp:ImageButton runat="server" ID="AddNewButton" AlternateText="Add New Quotation" ToolTip="Add New Quotation"
         OnClick="AddNewButton_Click" ImageUrl="~/Images/iAdd.PNG" />            
        </td> 
        <td>
        <asp:ImageButton runat="server" ID="DeleteButton" AlternateText="Delete Quotation" ToolTip="Delete Quotation"
         OnClick="DeleteButton_Click" ImageUrl="~/Images/iBin.gif" OnClientClick="return confirm('Enquiry details will be deleted! Do you want to continue ?')" />         
        </td> 
    </tr>
</table>
 
 </asp:Panel>   
  <br />
 <asp:Panel ID="SearchPanel" runat="server">
    <asp:GridView ID="EnquiryGridView" runat="server" AutoGenerateEditButton="false" OnPageIndexChanging="EnquiryGridView_PageIndexChanging"
    AutoGenerateDeleteButton="false" AutoGenerateColumns="false" SkinID="metro" OnRowCommand="EnquiryGridView_RowCommand"
    ShowFooter="true"   DataKeyNames="ID" DataSourceID="ODODS" 
         onrowdatabound="EnquiryGridView_RowDataBound" > <%--OnRowCreated="EnquiryGridView_RowCreated" --%> 
    
    <Columns>   
         
    <asp:TemplateField ItemStyle-Width="10px"> 
    <HeaderTemplate>
    <asp:ImageButton runat="server" ID="Copy" ImageUrl="~/Images/imgCopy.png" ToolTip="Create a copy from existing quotation" /> <%--OnClick="CopyBtnClick" --%>
    </HeaderTemplate>    
     <ItemTemplate>   
     <asp:RadioButton ID="rbtnSelect" runat="server" AutoPostBack="true"  OnCheckedChanged="SelectButton_Click" />       
     </ItemTemplate>  
    </asp:TemplateField>  
     <asp:TemplateField HeaderText="ID">
    <ItemTemplate>   
    <asp:HyperLink ID="cli" runat="server" NavigateUrl='<%# Eval("ID","~/Enquiry/Forms/ManageEnquiry.aspx?ID={0}") %>' Text='<%# Eval("ID") %>' Font-Underline="true"></asp:HyperLink>
    </ItemTemplate> 
    </asp:TemplateField>   
     
    <asp:TemplateField HeaderText="Customer/Vendor">
    <ItemTemplate>   
    <asp:Label ID="lblContact" runat="server" Text ='<%# Eval("Company") %>'></asp:Label>
    </ItemTemplate>     
    </asp:TemplateField>   
    <asp:TemplateField HeaderText="Contact Person">
    <ItemTemplate>   
    <asp:Label ID="lblContact1" runat="server" Text ='<%# Eval("ContactName") %>'></asp:Label>
    </ItemTemplate>     
    </asp:TemplateField>  
    
    <asp:TemplateField HeaderText="Product Suggested">
    <ItemTemplate>   
    <asp:Label ID="lblProductSuggested" runat="server" Text ='<%# Eval("ProductSuggested") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField>
    
    <asp:TemplateField HeaderText="Estimation">
    <ItemTemplate>   
    <asp:Label ID="lblEstimation" runat="server" Text ='<%# Eval("Estimation","{0:dd/MM/yyyy}") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField>
    
     <asp:TemplateField HeaderText="Product Status">
    <ItemTemplate>   
    <asp:Label ID="lblProductStatus" runat="server" Text ='<%# Eval("ProductStatus") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField>
    
     <asp:TemplateField HeaderText="Enquiry Status">
    <ItemTemplate>   
    <asp:Label ID="lblEnquiryStatus" runat="server" Text ='<%# Eval("EnquiryStatus") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField>
    
    <asp:TemplateField HeaderText="Follow Up Status">
    <ItemTemplate>   
    <asp:Label ID="lblFollowUpStatus" runat="server" Text ='<%# Eval("FollowUpStatus") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField> 
    
    <asp:TemplateField HeaderText="Assigned To">
    <ItemTemplate>   
    <asp:Label ID="lblAssignedTo" runat="server" Text ='<%# Eval("AssignedTo") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField> 
 
     <asp:TemplateField HeaderText="Closure Date">
    <ItemTemplate>   
    <asp:Label ID="lblClosureDate" runat="server" Text ='<%# Eval("ClosureDate","{0:dd/MM/yyyy}") %>'></asp:Label>
    </ItemTemplate> 
    </asp:TemplateField>
    
       </Columns>
</asp:GridView>
  </asp:Panel>
    
    <asp:ObjectDataSource ID="ODODS" runat="server" 
    TypeName="Enquiry.BusLogic.Enquiry" ConflictDetection="CompareAllValues"
    SelectMethod="GetEnquiries" DataObjectTypeName="Enquiry.Data.EnquiryData" >
    <SelectParameters>   
    <asp:ControlParameter ControlID="txtSearch"     Name="searchText" Type="String" ConvertEmptyStringToNull="true" />    
    <asp:ControlParameter ControlID="txtID"         Name="Id" Type="String" ConvertEmptyStringToNull="true" />    
    <asp:ControlParameter ControlID="txtCreatedBy"  Name="CreatedBy" Type="String" ConvertEmptyStringToNull="true" />    
    <asp:ControlParameter ControlID="txtCompany"    Name="Company" Type="String" ConvertEmptyStringToNull="true" />    
    
    </SelectParameters>    
    </asp:ObjectDataSource>
   </asp:Content>
