<%@ Page Language="C#" AutoEventWireup="True" CodeBehind="ManageProfile.aspx.cs" 
Inherits="Payroll.Forms.ManageProfile" MasterPageFile="~/Payroll/Payroll.Master" %>

<asp:Content ContentPlaceHolderID="main" runat="server">
    <div>
    <asp:UpdatePanel ID="ITUP" runat="server" UpdateMode="Conditional">
<ContentTemplate>
    <asp:Panel ID="EmployeeTypeBtnPanel" runat="server">
    <table cellpadding="2" border="0" cellspacing="0" width="1220px" style="height: 0px;">
            <tr>
                <td style="width: 5px;">
                    <asp:ImageButton ID="imgAdd" Height="20px" runat="server" ImageUrl="~/Payroll/Images/iADD.bmp"
                        AlternateText="Add" OnClick="imgAddItem_Click"  CausesValidation="false" ToolTip="Add ">
                    </asp:ImageButton>
                </td>
                <td style="width: 5px;">
                    <asp:ImageButton ID="imgEdit" Height="22px" runat="server" ImageUrl="~/Payroll/Images/iEdit.gif"
                        AlternateText="Edit" OnClick="imgEditItem_Click" ToolTip="Edit "></asp:ImageButton>
                </td>
                <td style="width: 5px;">
                    <asp:ImageButton ID="imgDelete" Height="22px" runat="server" ImageUrl="~/Payroll/Images/iDel.png"
                        AlternateText="Delete" OnClick="imgDeleteItem_Click" CausesValidation="false" ToolTip="Delete"
                        ></asp:ImageButton>
                </td>
                <td style="width: 5px;">
                    <asp:ImageButton ID="imgSave" Height="22px" runat="server" ImageUrl="~/Payroll/Images/iSave.gif"
                        AlternateText="Update" OnClick="imgUpdateItem_Click" ToolTip="Save "></asp:ImageButton>
                </td>
                <td style="width: 5px;">
                    <asp:ImageButton ID="imgCancel" Height="22px" runat="server" ImageUrl="~/Payroll/Images/iCan.gif"
                        AlternateText="Cancel" OnClick="imgCancelItem_Click" CausesValidation="false" ToolTip="Cancel">
                    </asp:ImageButton>
                </td>  
                 <td style="width: 5px;" align="left">
                </td>
                <td style="width: 1085px;">
                    <asp:HiddenField ID="hdnEditMode" Value="" runat="server" />
                </td>                      
            </tr>
        </table> 
    </asp:Panel>
    <asp:GridView ID="ItemsGridView" runat="server" AutoGenerateEditButton="false"
    AutoGenerateDeleteButton="false" AutoGenerateColumns="false" SkinID="metro"    
    ShowFooter="true" OnRowDataBound="ItemsGridView_RowDataBound" >  
    <Columns>        
        <asp:TemplateField HeaderText="Select">
         <ItemTemplate>
            <asp:CheckBox ID="cbSelect" EnableTheming="true" Font-Bold="true"
                runat="server"    />           
        </ItemTemplate>
        <EditItemTemplate>
         <asp:Label ID="ID" runat="server" Text='<%# Bind("ID") %>' CssClass="HiddenClass" ></asp:Label>         
        </EditItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Employee ID"  >      
            <ItemTemplate>
                <asp:Label ID="lblID" runat="Server" Width="100px" Text='<%# Eval("ID") %>' />
            </ItemTemplate>           
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Employee Name" >           
            <ItemTemplate>
                <asp:Label ID="lblName" runat="Server" Width="250px" Text='<%# Eval("EmpName") %>' />
            </ItemTemplate>
            <EditItemTemplate>              
                <asp:Label ID="lblName" runat="server" Width="250px" Text='<%# Eval("EmpName") %>' /> <%--OnTextChanged="ItemChanged" AutoPostBack="true" --%>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Employee Type" >           
            <ItemTemplate>
                <asp:Label ID="lblType" runat="Server" Width="250px" Text='<%# Eval("EmpTypeDescription") %>' />
            </ItemTemplate>
            <EditItemTemplate>              
              <asp:DropDownList ID="ddlEmpType" runat="server"   /> <%--OnTextChanged="ItemChanged" AutoPostBack="true" --%>
            </EditItemTemplate>
        </asp:TemplateField>
        <asp:TemplateField HeaderText="Basic Monthly" >           
            <ItemTemplate>
                 <asp:CheckBox ID="cbIBM" runat="server" Checked='<%# Eval("IsBasicMonthly") == DBNull.Value ? false : Eval("IsBasicMonthly") %>'   />    
            </ItemTemplate>
            <EditItemTemplate>              
              <asp:CheckBox ID="cbIBM" EnableTheming="true" Font-Bold="true"
                runat="server" Checked='<%# Eval("IsBasicMonthly") == DBNull.Value ? false : Eval("IsBasicMonthly") %>' /> 
            </EditItemTemplate>
        </asp:TemplateField>
        
           
       </Columns>
       </asp:GridView>
</ContentTemplate>
</asp:UpdatePanel>
   </div>
</asp:Content>